### ISSUE TITLE
ModuleNotFoundError: No module named 'Conversion'

### ISSUE THREAD

**Issue by edge2992** [lwgray/pyEntrezId#12]
Thank you for sharing the library. When I tried to use this library, I could not use it due to the following error.

I'm getting an error with Python 3.8.10, pip 20.0.2.

```
>>> import PyEntrezId
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/H/tutorial_material/bio_library/bio_library/lib/python3.8/site-packages/PyEntrezId/__init__.py", line 1, in <module>
    from Conversion import Conversion
ModuleNotFoundError: No module named 'Conversion'
```

**Comment by edge2992** [comment]
The path specified in PyEntrezId/__init__.py in the repository is correct, but the PyEntrezId/__init__.py path in dist/PyEtrezId-1.5.8.2.tar.gz seems to be incorrect.

**Comment by GuerreroVazquez** [comment]
Hi! 
I also encountered this issue. I think there was a mistake building the package because if you download the repo and just copy the folder "pyEntrezId" to your project, it works wonders.
