### ISSUE TITLE
pip install does not work

### ISSUE THREAD

**Issue by ifiddes** [lwgray/pyEntrezId#5]
Tried on both my local OSX machine and CentOS remote server.

```
juggernaut Tue May 17 09:16 ~ $pip install --upgrade pyEntrezId
You are using pip version 6.0.6, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting pyEntrezId
  Downloading PyEntrezId-1.5.7.tar.gz
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/scratch/tmp/pip-build-IHwvIG/pyEntrezId/setup.py", line 7, in <module>
        with open(os.path.join(HERE, 'README.rst')) as f:
    IOError: [Errno 2] No such file or directory: '/scratch/tmp/pip-build-IHwvIG/pyEntrezId/README.rst'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

      File "<string>", line 20, in <module>

      File "/scratch/tmp/pip-build-IHwvIG/pyEntrezId/setup.py", line 7, in <module>

        with open(os.path.join(HERE, 'README.rst')) as f:

    IOError: [Errno 2] No such file or directory: '/scratch/tmp/pip-build-IHwvIG/pyEntrezId/README.rst'

    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /scratch/tmp/pip-build-IHwvIG/pyEntrezId
```

However, it works fine if I install directly from github via `pip install git+https://github.com/lwgray/pyEntrezId.git`

**Comment by lwgray** [comment]
sorry @ifiddes ... I am working on it  - Thank you very much for the issue report!

Fixed it by deleting Reference to README file in Long Description attribute in setup.py file
